### ISSUE TITLE
Provide instructions on how to get a server IP and using metallb

### ISSUE THREAD

**Issue by spirasean** [MoJo2600/pihole-kubernetes#1]
If possible could you describe the steps you take to choose ServerIP. I am not able to get this working and am curious to see if I am missing something in this step.

**Comment by MoJo2600** [comment]
give me a minute i'll try to get something together

**Comment by MoJo2600** [comment]
@spirasean Have a look at the current master. I added the annotation for metallb to share the same ip adresses between the services and updated the readme accordingly. Though i could not test the deployment, because i have no access to my cluster this week. Maybe you want to test it out and tell me how it went.

**Comment by spirasean** [comment]
Awesome thanks I will test out tonight and get back to you.

**Comment by SeanChristopherConway** [comment]
So awesome this did work. Unfortunately, it is necessary to use 'Cluster' traffic policy and not 'Local' to have the two services share the same metallb IP, which causes the source ip to not be available in pihole. Also I needed to use loadBalancerIP to get the same IP with 'Cluster' traffic to work. Thanks

**Comment by MoJo2600** [comment]
@SeanChristopherConway i have it working @home with 'Local' traffic policy and it was working. I'll try to get the deployment i have @home and update the repository on the weekend when I'm home again.

**Comment by SeanChristopherConway** [comment]
@MoJo2600 Looking forward to it. Both of the methods you provided in the README do not work for me with externalTrafficPolicy local. Even if I limit the metallb address pool to one ip it still seems to hand out two different ips and if I use loadBalancerIp then the issue above occurs, ie. one service only shows pending for externalIP.

**Comment by MoJo2600** [comment]
@SeanChristopherConway @spirasean I updated the configuration to match my current setup, that is running here on my cluster. For me both things are working, the ip of the client in pihole and one ip for both services. My metallb version 0.7.3 set up with helm.
I had some issues with 0.7.3 especially, that i have to restart the speaker pods, after i changed something. They just stopped advertising the ip addresses.
Hope it helps.

**Comment by MoJo2600** [comment]
I'm currently working on a helm chart to deploy pihole with it. I think it makes things easier. Check out my branch helm-chart. It's not done yet, i'll keep you informed.

**Comment by SeanChristopherConway** [comment]
Awesome. Switching to use the metallb.universe.tf/address-pool: network-services seemed to solve my issue and now can use externalTrafficPolicy local. Will check out the helm-chart, thanks a ton! I have some questions about what you are doing with volumes and storage but perhaps this ticket is not the place.

**Comment by MoJo2600** [comment]
I will update the docs to provide information, but in short. Pi-hole stores everything you set in the website locally inside the pod. If you do not store this information inside a volume, all information is lost when you delete the pod.

Another thing: if you set the ServerIP to 0.0.0.0, the new default blocking mode NONE should be activated automatically. So there is no need anymore to know the external address beforehand. But maybe you should upgrade image version to 4.2.1 to have the latest version as well.

**Comment by MoJo2600** [comment]
Hey everybody, I now created a working helm chart and updated the version of pi-hole to 4.2.2. With the default blocking mode it is not longer necessary to set the ServerIP. It was even removed from 4.2.2. So, if you take the helm chart with an configured values.yaml (see README.md) pi-hole should work right out of the box, without any manual rework. Please open a new issue if you experience any problems.
