### ISSUE TITLE
DHCP leases should use loadbalanced IP if available

### ISSUE THREAD

**Issue by c-yco** [MoJo2600/pihole-kubernetes#104]
Currently the dhcp lease handed out to the clients uses the node IP where the pihole pod is running as the dns server. This means if  this nodes gets down or the pod is resheduled to another node dns requests from the clients fail. 

With bare metall LBs like metallb or purelb it should be possible to use the loadbalancer ip of the service instead as the dns server in the lease. 

The chart should be expanded that there is a switch to set dns server as the loadbalanced IP. I think during start of the pod this need to be requested from kubernetes api and then pushed into a config file for dnsmasq.

**Comment by vavallee** [comment]
Did you actually get DHCP to reply to requests without using hostnetwork?

**Comment by c-yco** [comment]
no, I am still using hostnetwork. But if the loadbalancer IP is used, a change of the node wont have any effect on the dns requests of the clients. 

Regarding getting rid of host network. I think this is not totally possible as dhcp is using broadcast. But it should be possible to create a pod which runs a dhcp proxy with host networking, and configure this proxy to forward the dhcp request to the pihole service. this way pihole wont need host network anymore.

**Comment by vavallee** [comment]
I think you are right, and it's a limitation of broadcast networking.

I ended up just using a nodeselector for the DNS host.

Good idea about the dhcp-proxy, I will look into this when I have time.

**Comment by c-yco** [comment]
Created https://github.com/MoJo2600/pihole-kubernetes/pull/133 for this

**Comment by MoJo2600** [comment]
I will close this issue as #133 has been merged.
