### ISSUE TITLE
Static DHCP entries are not persistent

### ISSUE THREAD

**Issue by vavallee** [MoJo2600/pihole-kubernetes#106]
I am using pihole as a DHCP server for my network.

Once this chart gets installed and is working, I went ahead and set all the DHCP settings in the web-interface

I then added all the static leases for my network devices.

However if the pod terminates, the static lease information is not persisted. It looks like all the other configs are persisted properly.
It looks like pihole is storing the static leases in

`./dnsmasq.d/04-pihole-static-dhcp.conf`

Is is possible to add persistence for this, or have a section for static leases in values.yaml?

**Comment by MoJo2600** [comment]
Could you test it with the latest version, #91 added a option to added static dhcp entries. This change should create the file you need. I'm currently not sure if the file is then writable.

```
  staticDhcpEntries: []
  # Static DHCP config
  # staticDhcpEntries:
  # - dhcp-host=MAC_ADDRESS,IP_ADDRESS,HOSTNAME
```

**Comment by vavallee** [comment]
Thank you, I will test it as soon as I have some time.

**Comment by MoJo2600** [comment]
I will close this issue due to inactivity. Feel free to comment if there is anything else.
