### ISSUE TITLE
Release chart on https://hub.helm.sh

### ISSUE THREAD

**Issue by MoJo2600** [MoJo2600/pihole-kubernetes#11]
The goal is to deploy this chart to https://hub.helm.sh so everbody has access to it.

**Comment by billimek** [comment]
The `helm/charts` repo is [being deprecated](https://github.com/helm/charts#deprecation-timeline), so helm hub is the path forward.

@MoJo2600, I have a solid github actions implementation that will lint and test charts (via KIND) for all pull requests and then automatically publish charts as a repo release.

I'm going to submit a PR to implement the github actions in this in repo, but to fully implement it will require you (or someone else with admin access to this repo) to finalize the implementation.  Specifically, github pages will need to be enabled (ideally using the default `gh-pages` branch), and a github personal access token or equivalent will need to be added as a github actions secret in the repo configuration.

Any issues with this approach?

**Comment by MoJo2600** [comment]
Very nice! I will enable everything and add the secret. Thank you!

**Comment by billimek** [comment]
Thanks for merging #23 @MoJo2600!  There seems to be a problem with the helm chart tester thing expecting the chart(s) to live in their own dedicated subdirectory (e.g. `charts/pihole` instead of `pihole`) - I'm looking for a workaround now as that limitation seems silly.

**Comment by MoJo2600** [comment]
Yeah, but be could also rename the directories as well... I already thought about deleting the not helm setup in the repo, because I'm not maintaining them

**Comment by billimek** [comment]
The directory issue appears to be solved (via #26).  Still looking into the chart-test install issue described in #27.  As a last resort, we could disable the CI steps that install the KIND cluster and run a chart test, but that really shouldn't be necessary.

**Comment by MoJo2600** [comment]
Yes please go ahead if you have the time to do this. Please don't apologize, I'm so glad, that somebody finds my code useful and is willing to invest time in it :+1:

**Comment by billimek** [comment]
https://github.com/helm/hub/pull/237 submitted to add this repo!

**Comment by billimek** [comment]
@MoJo2600 do you mind commenting on https://github.com/helm/hub/pull/237?  They want to make sure you agree to add this repo to Helm Hub.

**Comment by MoJo2600** [comment]
Done!

**Comment by billimek** [comment]
With the merge of [this helm hub PR](https://github.com/helm/hub/pull/237) and commit [4283539892041590588051e0415252a338ba5a0d](https://github.com/MoJo2600/pihole-kubernetes/commit/4283539892041590588051e0415252a338ba5a0d) (which makes https://mojo2600.github.io/pihole-kubernetes/ look pretty).

The chart is now [hosted on helm hub](https://hub.helm.sh/charts/mojo2600/pihole) and this issue can be closed IMO.

**Comment by MoJo2600** [comment]
Very very cool! That was a nice piece of work, thank you!
