### ISSUE TITLE
Readonly Pod on NFS

### ISSUE THREAD

**Issue by Stone2971** [MoJo2600/pihole-kubernetes#129]
If i deploy a pihole pod with helm on my k3s cluster on the local storage class all work well.
If i deploy a pihole pod with helm on my k3s cluster on my nfs storage class i cant add dns entries or blacklist entries.
I always get this error:

> Error, something went wrong!
> While executing INSERT OT IGNORE: attempt to write a readonly database
> Added 0 out of 1 domains

I use the nfs provider from 
[https://github.com/kubernetes-sigs/nfs-subdir-external-provisioner](https://github.com/kubernetes-sigs/nfs-subdir-external-provisioner)
and it was installed via helm.

For the pihole installation i test this line
`helm install pihole mojo2600/pihole --set DNS1="1.1.1.1" --set DNS2="8.8.8.8" --set adminPassword="asdf" --set replicaCount="1" --set serviceDns.type="LoadBalancer" --set serviceWeb.type="LoadBalancer"  --set persistentVolumeClaim.enabled="true"`

I dont get any information about the logs.

What can be wrong?
Thank You.

**Comment by MoJo2600** [comment]
We had this issue a few times now. Please have a look here, if this resolves your problem: https://github.com/MoJo2600/pihole-kubernetes/issues/39#issuecomment-701169533

**Comment by Stone2971** [comment]
Thank you. This was the problem.
Yes NFS groups and NFSv4 are often a problem.

My deployment works and i can save data. Yeeha ;-)

**Comment by MoJo2600** [comment]
I added a topic under discussions Q&A because it seems like a lot of people have the same issue  https://github.com/MoJo2600/pihole-kubernetes/discussions/130
