### ISSUE TITLE
chart.yaml appVersion and image.tag diverge

### ISSUE THREAD

**Issue by morremeyer** [MoJo2600/pihole-kubernetes#152]
I just noticed that the `appVersion` in Chart.yaml and the `image.tag` in values.yaml have diverged.

As `appVersion` is optional, I’d go with removing it altogether and updating `image.tag` only in the future.

The other variant would be to default the pihole container in the Deployment to `{{ .Chart.appVersion }}` and unset `image.tag`.

@MoJo2600, which one do you prefer? I’d open a pull request for any of the two.

**Comment by MoJo2600** [comment]
I think removing the optional `appVersion` is a good approach. I'd be very happy if you would create a pull request for this.
