### ISSUE TITLE
Rancher Repo Add Has Issues

### ISSUE THREAD

**Issue by mitchross** [MoJo2600/pihole-kubernetes#169]
It appears alot the helm chart config is missing when adding the repo manually to Rancher. Notice the install version is 1.7.6 and no option for 2.0.0

![image](https://user-images.githubusercontent.com/6330506/127425486-7bdcaa7f-36cc-45d2-a7bc-d968a3aa20c7.png)

![image](https://user-images.githubusercontent.com/6330506/127425447-a7ec94c5-73a3-40c3-8ffd-780ca587c8ed.png)

![image](https://user-images.githubusercontent.com/6330506/127425607-09859fb7-780d-4a17-aae2-c6c2ebdaf5e8.png)

**Comment by MoJo2600** [comment]
Oh, that is not good. Thanks for the Info. I will check what changed between 1.x and 2.x.

**Comment by mitchross** [comment]
Looking closer it might be around this time. https://github.com/MoJo2600/pihole-kubernetes/compare/1.2.0...pihole-1.2.1

as 1.20 is the last version in rancher

**Comment by MoJo2600** [comment]
I don't have a rancher installation at hand. But when I read the documentation right, it states that rancher is able to read from [helm chart repositories](https://rancher.com/docs/rancher/v2.x/en/helm-charts/legacy-catalogs/catalog-config/#custom-helm-chart-repository). So the correct url to add should be `https://mojo2600.github.io/pihole-kubernetes/`

**Comment by mitchross** [comment]
@MoJo2600  that worked! thanks!
