### ISSUE TITLE
Possible incorrect path for healthchecks?

### ISSUE THREAD

**Issue by paul999** [MoJo2600/pihole-kubernetes#177]
I am not 100% sure this is a actual issue, so didn't directly want to create a pull request. If someone can confirm this is a actual issue, I can create a PR for this.

I noticed when deploying this, that the healthchecks ( https://github.com/MoJo2600/pihole-kubernetes/blob/master/charts/pihole/templates/deployment.yaml#L191-L200 ) are using admin.index.php as path. On my pihole instance this shows a page as blocked by pihole. Should the check be done on admin/index.php instead?

**Comment by MoJo2600** [comment]
Yes, I think the path is wrong, but it still works. Please feel free to open a pull request. I'm happy to merge it.
