### ISSUE TITLE
MixedProtocols - Mixed DNS Service

### ISSUE THREAD

**Issue by muhlba91** [MoJo2600/pihole-kubernetes#178]
Hi,

with the new feature gate `MixedProtocolLBService` from `1.20` onwards, mixed LB services are possible. Can #78 reopened and integrated through a setting (e.g. `mixedDnsService`)?

**Comment by MoJo2600** [comment]
I reopened the issue, but this will be a breaking change I suppose?

**Comment by muhlba91** [comment]
I was thinking about something like:

`values.yaml`:
```
serviceDns:
  mixedProtocol: false
```

The current `service-dns-tcp.yaml` and `service-dns-udp.yaml` I'd wrap in:
```
{{- if not .Values.serviceDns.mixedProtocol }}
...
{{- end }}
```

Additionally, create a new `service-dns.yaml` containing TCP and UDP wrapped around:
```
{{- if .Values.serviceDns.mixedProtocol }}
...
{{- end }}
```

This way, backwards compatibility is given and defaulting to the current behaviour of generating separate services, but users can opt-in to using a mixed service if they enabled the feature gate.
What do you think?

**Comment by MoJo2600** [comment]
Sounds very good!

**Comment by muhlba91** [comment]
created a PR in #179 adding the flag as discussed.
