### ISSUE TITLE
error: error parsing deployment-pihole.yml: error converting YAML to JSON: yaml: line 52: did not find expected key

### ISSUE THREAD

**Issue by zobelhelas** [MoJo2600/pihole-kubernetes#2]
Wrong indenting here:

https://github.com/MoJo2600/pihole-kubernetes/blob/1c860311741007c47d51931218c2ee7968b947f7/deployment-pihole.yml#L53

**Comment by MoJo2600** [comment]
Thank you! I fixed it.
