### ISSUE TITLE
Setting   externalTrafficPolicy: Local Pihole doesn't work.

### ISSUE THREAD

**Issue by i5Js** [MoJo2600/pihole-kubernetes#20]
After several days trying to get this working finally I got it, but the problem comes when I set the   externalTrafficPolicy: to Local. The Pihole stop to work, the http service is working fine, but the DNS doesn't . You can find below my service configuration:

pi@raspserverM:~/k3s/pihole $ cat svc-pihole-tcp.yml 
---
apiVersion: v1
kind: Service
metadata:
  annotations:
    metallb.universe.tf/address-pool: pool-home
    metallb.universe.tf/allow-shared-ip: pihole-svc
  name: pihole-tcp
  labels:
    app: pihole
spec:
  externalTrafficPolicy: Local
  type: LoadBalancer
  ports:
  - protocol: TCP
    port: 9888
    targetPort: pihole-http
    name: pihole-http
  - protocol: TCP
    port: 53
    targetPort: pihole-dns-tcp
    name: pihole-dns-tcp
  selector:
    app: pihole

pi@raspserverM:~/k3s/pihole $ cat svc-pihole-udp.yml 
---
apiVersion: v1
kind: Service
metadata:
  annotations:
    metallb.universe.tf/allow-shared-ip: pihole-svc
  name: pihole-udp
  labels:
   app: pihole
spec:
  externalTrafficPolicy: Local
  type: LoadBalancer
  ports:
  - protocol: UDP
    port: 53
    targetPort: pihole-dns-udp
    name: pihole-dns-udp
  selector:
    app: pihole

And the Metallb config as well:

pi@raspserverM:~/k3s/pihole $ cat ../core/metallb-configmap.yml 
apiVersion: v1
kind: ConfigMap
metadata:
  namespace: metallb-system
  name: config
data:
  config: |
    address-pools:
    - name: pool-home
      protocol: layer2
      addresses:
      - 192.168.1.120-192.168.1.125

I'm using the classic version instead helms

**Comment by MoJo2600** [comment]
Could you provide logs or maybe a describe of the service, after it stopped working? This is a sample of a working service definition that i took from my helm setup. Maybe it helps:

```
apiVersion: v1
kind: Service
metadata:
  annotations:
    metallb.universe.tf/allow-shared-ip: pihole-svc
  creationTimestamp: "2019-08-04T13:07:51Z"
  labels:
    app: pihole
    chart: pihole-1.0.0
    heritage: Tiller
    release: pihole
  name: pihole-tcp
  namespace: dns
  resourceVersion: "48630410"
  selfLink: /api/v1/namespaces/dns/services/pihole-tcp
  uid: dd8cce3e-b6b8-11e9-a386-d4bed9ec2878
spec:
  clusterIP: 10.99.197.184
  externalTrafficPolicy: Local
  healthCheckNodePort: 31368
  loadBalancerIP: 192.168.178.252
  ports:
  - name: http
    nodePort: 30552
    port: 80
    protocol: TCP
    targetPort: http
  - name: https
    nodePort: 30252
    port: 443
    protocol: TCP
    targetPort: https
  - name: dns
    nodePort: 30643
    port: 53
    protocol: TCP
    targetPort: dns
  selector:
    app: pihole
    release: pihole
  sessionAffinity: None
  type: LoadBalancer
status:
  loadBalancer:
    ingress:
    - ip: 192.168.178.252
```

**Comment by i5Js** [comment]
Hi, 

Many thanks for your answer. I think I get the issue fixed, almost. The problem was I'm using k3s with traeffic and it seems it's not working fine with Metallb, so I remove treaffic and now it's working almost fine. And I say almost fine, because there are some services "pending"

pi@raspserverM:~/k3s/pihole $ kubectl get pod -A
NAMESPACE        NAME                                      READY   STATUS    RESTARTS   AGE
kube-system      metrics-server-6d684c7b5-5vg5n            1/1     Running   0          40h
kube-system      coredns-d798c9dd-p2zwx                    1/1     Running   0          40h
metallb-system   speaker-rr8bb                             1/1     Running   0          39h
metallb-system   speaker-hcp4t                             1/1     Running   0          39h
kube-system      local-path-provisioner-58fb86bdfd-96tcn   1/1     Running   15         40h
metallb-system   speaker-2l44k                             1/1     Running   1          39h
metallb-system   controller-57967b9448-g4z6l               1/1     Running   0          39h
default          phpfpm-77b748fc84-q48gn                   1/1     Running   0          15h
dns-home         svclb-pihole-tcp-qsx2v                    0/2     Pending   0          3h4m
dns-home         svclb-pihole-tcp-wtrww                    0/2     Pending   0          3h4m
dns-home         svclb-pihole-udp-tdd7c                    1/1     Running   0          3h4m
dns-home         svclb-pihole-tcp-vllc9                    2/2     Running   0          3h4m
dns-home         svclb-pihole-udp-4qxnq                    1/1     Running   0          3h4m
dns-home         svclb-pihole-udp-fgj9g                    0/1     Pending   0          3h4m
dns-home         pihole-7767fd9b7d-8z9rn                   1/1     Running   0          25m

**Comment by MoJo2600** [comment]
Hey, is it now working? I strongly reccoment to try the helm chart, as it is properly maintained. 
Otherwise, i might help, if you could do a describe on the Pending services and post it here?

**Comment by i5Js** [comment]
Hey!Thanks for your answer. Yes, it's working now, the problem was , I'm using k3s instead k8s and it comes with traeffic, so I installed k3s without it and it works now. however, the services, sometimes are pending:

**dns-home         svclb-pihole-tcp-qsx2v                    0/2     Pending   0          21d**
**dns-home         svclb-pihole-tcp-wtrww                    0/2     Pending   0          21d**
dns-home         svclb-pihole-udp-tdd7c                    1/1     Running   0          21d
dns-home         svclb-pihole-tcp-vllc9                    2/2     Running   0          21d
dns-home         svclb-pihole-udp-4qxnq                    1/1     Running   0          21d
**dns-home         svclb-pihole-udp-fgj9g                    0/1     Pending   0          21d**


pi@raspserverM:~ $ kubectl describe pod svclb-pihole-tcp-qsx2v -n dns-home
Name:           svclb-pihole-tcp-qsx2v
Namespace:      dns-home
Priority:       0
Node:           <none>
Labels:         app=svclb-pihole-tcp
                controller-revision-hash=7b4b8b8cbf
                pod-template-generation=1
                svccontroller.k3s.cattle.io/svcname=pihole-tcp
Annotations:    <none>
Status:         Pending
IP:             
IPs:            <none>
Controlled By:  DaemonSet/svclb-pihole-tcp
Containers:
  lb-port-9888:
    Image:      rancher/klipper-lb:v0.1.2
    Port:       9888/TCP
    Host Port:  9888/TCP
    Environment:
      SRC_PORT:    9888
      DEST_PROTO:  TCP
      DEST_PORT:   9888
      DEST_IP:     10.43.249.202
    Mounts:
      /var/run/secrets/kubernetes.io/serviceaccount from default-token-4n2ff (ro)
  lb-port-53:
    Image:      rancher/klipper-lb:v0.1.2
    Port:       53/TCP
    Host Port:  53/TCP
    Environment:
      SRC_PORT:    53
      DEST_PROTO:  TCP
      DEST_PORT:   53
      DEST_IP:     10.43.249.202
    Mounts:
      /var/run/secrets/kubernetes.io/serviceaccount from default-token-4n2ff (ro)
Conditions:
  Type           Status
  PodScheduled   False 
Volumes:
  default-token-4n2ff:
    Type:        Secret (a volume populated by a Secret)
    SecretName:  default-token-4n2ff
    Optional:    false
QoS Class:       BestEffort
Node-Selectors:  <none>
Tolerations:     node.kubernetes.io/disk-pressure:NoSchedule
                 node.kubernetes.io/memory-pressure:NoSchedule
                 node.kubernetes.io/not-ready:NoExecute
                 node.kubernetes.io/pid-pressure:NoSchedule
                 node.kubernetes.io/unreachable:NoExecute
                 node.kubernetes.io/unschedulable:NoSchedule
Events:
  Type     Reason            Age        From               Message
  ----     ------            ----       ----               -------
  Warning  FailedScheduling  <unknown>  default-scheduler  0/3 nodes are available: 2 node(s) didn't match node selector, 3 node(s) didn't have free ports for the requested pod ports.


pi@raspserverM:~ $ kubectl describe pod svclb-pihole-udp-fgj9g -n dns-home
Name:           svclb-pihole-udp-fgj9g
Namespace:      dns-home
Priority:       0
Node:           <none>
Labels:         app=svclb-pihole-udp
                controller-revision-hash=5b669f5dd5
                pod-template-generation=1
                svccontroller.k3s.cattle.io/svcname=pihole-udp
Annotations:    <none>
Status:         Pending
IP:             
IPs:            <none>
Controlled By:  DaemonSet/svclb-pihole-udp
Containers:
  lb-port-53:
    Image:      rancher/klipper-lb:v0.1.2
    Port:       53/TCP
    Host Port:  53/TCP
    Environment:
      SRC_PORT:    53
      DEST_PROTO:  UDP
      DEST_PORT:   53
      DEST_IP:     10.43.145.215
    Mounts:
      /var/run/secrets/kubernetes.io/serviceaccount from default-token-4n2ff (ro)
Conditions:
  Type           Status
  PodScheduled   False 
Volumes:
  default-token-4n2ff:
    Type:        Secret (a volume populated by a Secret)
    SecretName:  default-token-4n2ff
    Optional:    false
QoS Class:       BestEffort
Node-Selectors:  <none>
Tolerations:     node.kubernetes.io/disk-pressure:NoSchedule
                 node.kubernetes.io/memory-pressure:NoSchedule
                 node.kubernetes.io/not-ready:NoExecute
                 node.kubernetes.io/pid-pressure:NoSchedule
                 node.kubernetes.io/unreachable:NoExecute
                 node.kubernetes.io/unschedulable:NoSchedule
Events:
  Type     Reason            Age        From               Message
  ----     ------            ----       ----               -------
  Warning  FailedScheduling  <unknown>  default-scheduler  0/3 nodes are available: 2 node(s) didn't match node selector, 3 node(s) didn't have free ports for the requested pod ports.


Many thanks again for your help. 

Happy 2020!!

**Comment by MoJo2600** [comment]
You should focus on the error message `Warning FailedScheduling default-scheduler 0/3 nodes are available: 2 node(s) didn't match node selector, 3 node(s) didn't have free ports for the requested pod ports.`

The error that is happening is the following. Let's break it down in two parts:
`FailedScheduling default-scheduler 0/3 nodes are available: 2 node(s) didn't match node selector`: Your node selector only matches one node. So the service will only be deployed one node based on the Node-Selectors. 

`3 node(s) didn't have free ports for the requested pod ports.`: This is the main reason it is not working. Pihole will create a custom DNS server. This DNS server will utilize port 53 UDP and 53 TCP. It looks like your setup will try to use this ports on the node itself not on a load blancer? Often this ports are already taken by the systemd DNS resolver. If the port is available the first container will claim those ports and no other pod will be able to use them. In my setup, a load balancer is created with a unique IP address and so the port 53 is mapped to a container port inside the cluster. So i'm able to have port 53 mapped multiple times, because it is not bound to the node.

One hint: If you use the the "Insert code" formatting in the github editor to paste your code, it will be better readable, because the indentation will be kept as it is.

Happy 2020 to you as well!

**Comment by i5Js** [comment]
Hi, many thanks for your help!

Yes, you’re right, the issue is the port which is in use. And yes I guess it uses the node instead the load balancer. How can I change this? 

My apologies about the code insert. I will use next time.

Again, many thanks for your time and help.

**Comment by i5Js** [comment]
I was checking my metallb config file, I think it's right, but your're the expert here:
`pi@raspserverM:~/k3s/core $ cat metallb-configmap.yml
apiVersion: v1
kind: ConfigMap
metadata:
  namespace: metallb-system
  name: config
data:
  config: |
    address-pools:
    - name: pool-dns
      protocol: layer2
      addresses:
      - 192.168.1.120-192.168.1.121
    - name: services
      protocol: layer2
      addresses:
      - 192.168.1.122-192.168.1.126`

The IPs in the pool-dns, I guess, are for map the ports right? Should I add one more since I have three nodes? I will try

**Comment by i5Js** [comment]
The strange thing here or I can understand it is this:

>pi@raspserverM:~/k3s/pihole $ kubectl describe pod svclb-pihole-udp-sr8sv -n dns-home
> Name:           svclb-pihole-udp-sr8sv
> Namespace:      dns-home
> Priority:       0
> Node:           <none>
> Labels:         app=svclb-pihole-udp
>                 controller-revision-hash=f75877bbd
>                 pod-template-generation=1
>                 svccontroller.k3s.cattle.io/svcname=pihole-udp
> Annotations:    <none>
> Status:         Pending
> IP:
> IPs:            <none>
> Controlled By:  DaemonSet/svclb-pihole-udp
> Containers:
>   lb-port-53:
>     Image:      rancher/klipper-lb:v0.1.2
**>     Port:       53/TCP
>     Host Port:  53/TCP**
>     Environment:
**>       SRC_PORT:    53
>       DEST_PROTO:  UDP
>       DEST_PORT:   53**
>       DEST_IP:     10.43.61.170
By default is using TCP port, which is obiously in use, but the service is por UDP protocol...

And the second thing is 
The pods are in pending:

> pi@raspserverM:~/k3s/pihole $ kubectl get pod -n dns-home  $
> NAME                     READY   STATUS    RESTARTS   AGE
> pihole-c9bc5777-kptsj    1/1     Running   0          24d
> svclb-pihole-tcp-lthrd   2/2     Running   0          119m
> svclb-pihole-tcp-6rjpt   2/2     Running   0          119m
> svclb-pihole-tcp-fd7vc   2/2     Running   0          119m
**> svclb-pihole-udp-sr8sv   0/1     Pending   0          6m5s
> svclb-pihole-udp-jd9fz   0/1     Pending   0          6m5s
> svclb-pihole-udp-tn8xz   0/1     Pending   0          6m5s** 

But the services are working:

> pi@raspserverM:~/k3s/pihole $ kubectl get svc -n dns-home
> NAME         TYPE           CLUSTER-IP     EXTERNAL-IP     PORT(S)                       AGE
> pihole-udp   LoadBalancer   10.43.61.170   192.168.1.120   53:30026/UDP                  7m28s
> pihole-tcp   LoadBalancer   10.43.73.43    192.168.1.120   9888:30018/TCP,53:30751/TCP   120m

Sorry, I'm very noob with this.

**Comment by i5Js** [comment]
I think I know which is the problem... the k3s service on the nodes is not working properly:

> pi@raspserverN1:~ $ sudo systemctl status k3s
> ● k3s.service - Lightweight Kubernetes
>    Loaded: loaded (/etc/systemd/system/k3s.service; enabled; vendor preset: enabled)
>    Active: activating (auto-restart) (Result: exit-code) since Thu 2020-01-09 09:22:31 GMT; 3s ago
>      Docs: https://k3s.io
>   Process: 2768 ExecStartPre=/sbin/modprobe br_netfilter (code=exited, status=0/SUCCESS)
>   Process: 2770 ExecStartPre=/sbin/modprobe overlay (code=exited, status=0/SUCCESS)
>   Process: 2772 ExecStart=/usr/local/bin/k3s server (code=exited, status=255/EXCEPTION)
>  Main PID: 2772 (code=exited, status=255/EXCEPTION)

and

> pi@raspserverN2:~ $ sudo systemctl status k3s
> ● k3s.service - Lightweight Kubernetes
>    Loaded: loaded (/etc/systemd/system/k3s.service; enabled; vendor preset: enabled)
>    Active: activating (auto-restart) (Result: exit-code) since Thu 2020-01-09 09:23:20 GMT; 3s ago
>      Docs: https://k3s.io
>   Process: 29865 ExecStartPre=/sbin/modprobe br_netfilter (code=exited, status=0/SUCCESS)
>   Process: 29867 ExecStartPre=/sbin/modprobe overlay (code=exited, status=0/SUCCESS)
>   Process: 29869 ExecStart=/usr/local/bin/k3s server (code=exited, status=255/EXCEPTION)
>  Main PID: 29869 (code=exited, status=255/EXCEPTION)
> 
> Jan 09 09:23:20 raspserverN2 systemd[1]: k3s.service: Main process exited, code=exited, status=255/EXCEPTION
> Jan 09 09:23:20 raspserverN2 systemd[1]: k3s.service: Failed with result 'exit-code'.

I need to figure out what is happening.

**Comment by MoJo2600** [comment]
Unfortunately i have no experience with k3s. But if you find the error, let me know what it was.

**Comment by i5Js** [comment]
Well, problem fixed, as I said on my previous post, the problem was the nodes was flapping from up to down and up again all the time, because of that, never was some node available and the services were pending. I’ve upgraded k3s to the latest version and now is working flawless.

K3s and K8s and very similar, k3s is recommended for raspberry because it needs less resources but basically it’s the same, so if you are a “master” with k8s you are with k3s as well ;)

I’ll try now with helm chart ;)

Again many thanks for all you help and time with me ;)

**Comment by MoJo2600** [comment]
Good to know that you figured it out. I'll close the issue, feel free to come back if you have questions.
