### ISSUE TITLE
Feature request: add option to disable admin password

### ISSUE THREAD

**Issue by wyvernzora** [MoJo2600/pihole-kubernetes#251]
*Use case*
I am using Traefik ingress with ForwardAuth middleware, so I am looking for an option to disable the admin password as it is redundant. I noticed that if I set the password to empty string, this Helm chart generates a random one instead. I would like to request an option to explicitly disable the admin password.

*Proposed implementation*
 - Add a `disablePassword` boolean option to the `values.yaml`
 - If the option is true, set the password to empty string, thus disabling it

Would be happy to submit a PR if/when we agree on an approach.

**Comment by MoJo2600** [comment]
I think this is a great idea. I'm happy to merge a pull request.

**Comment by CygnusHyoga** [comment]
I've it working. I don't know how to make a pull request :-(

values.yaml

`adminPassword: ""`

secret.yaml

`{{- if not .Values.admin.existingSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ template "pihole.password-secret" . }}
  labels:
    app: {{ template "pihole.name" . }}
    chart: {{ template "pihole.chart" . }}
    heritage: {{ .Release.Service }}
    release: {{ .Release.Name }}
type: Opaque
data:
  {{- if .Values.adminPassword }}
  password: {{ .Values.adminPassword | b64enc | quote }}
  {{- else }}
  password: ""
  {{- end }}
{{- end }}`
