### ISSUE TITLE
Problem with Perstistent Volume

### ISSUE THREAD

**Issue by electropolis** [MoJo2600/pihole-kubernetes#302]
The tutorials says 

```
persistentVolumeClaim:
  enabled: true
```

in our values. But when deploying I get stuck on pods creation 
`no persistent volumes available for this claim and no storage class is set`

**Comment by i5Js** [comment]
It seems you are not using the storage class to provision the storage.

**Comment by MoJo2600** [comment]
You need to either set a default storage class or define it with `storageClass`. But I see that the setting is missing in the documentation. But you can see it in https://github.com/MoJo2600/pihole-kubernetes/blob/main/charts/pihole/values.yaml
