### ISSUE TITLE
chart in this repo, is different to chart in the helm repo? App version different.

### ISSUE THREAD

**Issue by jurgenweber** [MoJo2600/pihole-kubernetes#305]
```
$ helm search repo pihole
NAME         	CHART VERSION	APP VERSION	DESCRIPTION
pihole/pihole	2.24.0       	2024.05.0  	Installs pihole in kubernetes
```

but https://github.com/MoJo2600/pihole-kubernetes/blob/main/charts/pihole/Chart.yaml

says app version is 2024.06.0, not sure why the App Version is different?

**Comment by cbgbt** [comment]
Not the maintainer, but your answer is in [the Git changelog](https://github.com/MoJo2600/pihole-kubernetes/commits/main/charts/pihole/Chart.yaml):
* GitHub Actions robot updated `pihole` to `2024.06.0` [here](https://github.com/MoJo2600/pihole-kubernetes/commit/7f96afce866cd2dadfbb7d717ad05b87e23538a4)
* But the last release of the helm chart was [about a month prior](https://github.com/MoJo2600/pihole-kubernetes/commit/870d1f3691c6035c4315e1427950339f1dfbf06c)

**Comment by MoJo2600** [comment]
I'll have to have a look at this. I automated the update process when a new version of pihole is released. But I think the minor version of the chart should be increased as well even if the chart itself has not changed.

**Comment by MoJo2600** [comment]
@jurgenweber You are right, the version does not match, I will have a look.

**Comment by cbgbt** [comment]
@MoJo2600 It looks like that would be handled in https://github.com/MoJo2600/pihole-kubernetes/pull/304

**Comment by MoJo2600** [comment]
@cbgbt of yourse... i should go and merge the releases after they are created

**Comment by MoJo2600** [comment]
@jurgenweber I merged the pull request and now the new version is released as it should.
