### ISSUE TITLE
No response for dhcp?

### ISSUE THREAD

**Issue by JayG-EBSCO** [MoJo2600/pihole-kubernetes#37]
You've written an excellent guide, and with it I've been able to transfer my Pihole install for DNS from docker to kubernetes. My docker install was also acting as my home lan DHCP server, but I have not been able to get a DHCP response out of the kubernetes hosted instance. Have you tried to do so, and has there been any success?

**Comment by MoJo2600** [comment]
Hi, thank you. I think you might manage to do it, if you open up port 67 UDP and port 647 TCP in the service for pihole. But i never tested this.

**Comment by MoJo2600** [comment]
Closing this issue because there has been no response
