### ISSUE TITLE
Can't run TCP and UDP on same port with metalLB

### ISSUE THREAD

**Issue by zjael** [MoJo2600/pihole-kubernetes#4]
When setting up the tcp and udp services i run into this issue
Warning FailedScheduling: X node(s) didn't have free ports for the requested pod ports.
Using metalLB v0.7.3

Did you experience anything similar or what version of metalLB do you use?

**Comment by MoJo2600** [comment]
Hey, i have version 0.7.3 running. But i never got this error. I'm not sure if this is related to metallb. Which version of kubernetes are you running. The only reference I found to this error is related to a bug in 1.11.x and was fixed in 1.11.3.

**Comment by zjael** [comment]
Thanks for the fast response, well i am currently running k3s v0.2.0 which is based on k8s v1.13.4 i believe, so could be that k3s is the issue, though it seems odd. I will keep digging. :)

**Comment by MoJo2600** [comment]
Keep me informed about any progress you made. I did not yet test k3s but would appreciate any information.
