### ISSUE TITLE
LoadBalancer won't route trafic to pods

### ISSUE THREAD

**Issue by danyhoron** [MoJo2600/pihole-kubernetes#5]
Hi,

First, thank you for this great project and explanation.

I managed to get it to run but there's an issue w/ metalLB.
Both services (TCP / UDP) look allright,
![image](https://user-images.githubusercontent.com/9220101/55099431-54ecd800-50c8-11e9-8c6c-7f194ff34f1b.png)

but when I navigate to my ip, or telnet on any of the TCP ports, it doesn't work, I get: `Network is unreachable`.
If I open the node's IP w/ NodePort in the browser, it works, I can see pihole's admin web.

Here's what I get when I describe the tcp service:
![image](https://user-images.githubusercontent.com/9220101/55099642-b745d880-50c8-11e9-85eb-ba1fcfec35a9.png)

How can I troubleshoot it?

Thank you.

**Comment by danyhoron** [comment]
After deleting the services, and re-creating them w/ a new IP, it started working.
I think it's a metalLB issue.

**Comment by MoJo2600** [comment]
Yes, that is definately a metalLB issue. I hope this is fixed in the next version. Thanks for sharing the solution.
