### ISSUE TITLE
Liveness probe failure

### ISSUE THREAD

**Issue by 11jwolfe2** [MoJo2600/pihole-kubernetes#57]
I have been using version 4.4 of pi-hole for awhile now and went to update to version 5. When running on my cluster I get this error, that keeps pihole from starting.

`kubelet, kube-worker-1  Readiness probe failed: Get http://10.42.1.14:80/admin.index.php: dial tcp 10.42.1.14:80: connect: connection refused`

However If I uninstall the failed version 5 and roll back to 4.4, simply only changing the app version in values.yaml. It runs without issue.

I will provide any more details as needed. Just trying to figure out this issue.

**Comment by MoJo2600** [comment]
Can you paste the output of the container log? I have version 5 running and it is working for me. I think there is a error during startup of the container.

**Comment by 11jwolfe2** [comment]
`kubectl logs pihole-65466fd47f-l5xlc -n pihole
`
outputs, but when it fails the log is reset, so it took me a few tries to get the whole thing.

[s6-init] making user provided files available at /var/run/s6/etc...exited 0.
[s6-init] ensuring user provided files have correct perms...exited 0.
[fix-attrs.d] applying ownership & permissions fixes...
[fix-attrs.d] 01-resolver-resolv: applying... 
[fix-attrs.d] 01-resolver-resolv: exited 0.
[fix-attrs.d] done.
[cont-init.d] executing container initialization scripts...
[cont-init.d] 20-start.sh: executing... 
 ::: Starting docker specific checks & setup for docker pihole/pihole
OK: Checks passed for /etc/resolv.conf DNS servers

nameserver 127.0.0.1
nameserver 8.8.8.8
  [i] Existing PHP installation detected : PHP version 7.0.33-0+deb9u7

  [i] Installing configs from /etc/.pihole...
  [i] Existing dnsmasq.conf found... it is not a Pi-hole file, leaving alone!
  [✓] Copying 01-pihole.conf to /etc/dnsmasq.d/01-pihole.conf
chown: changing ownership of '/etc/pihole/pihole-FTL.conf': Operation not permitted
chown: cannot access '': No such file or directory
chmod: cannot access '': No such file or directory
chown: changing ownership of '/etc/pihole': Operation not permitted
chown: cannot access '/etc/pihole/dhcp.leases': No such file or directory
::: Pre existing WEBPASSWORD found
Using default DNS servers: 8.8.8.8 & 8.8.4.4
DNSMasq binding to default interface: eth0
Added ENV to php:
			"PHP_ERROR_LOG" => "/var/log/lighttpd/error.log",
			"ServerIP" => "0.0.0.0",
			"VIRTUAL_HOST" => "pi.hole",
Using IPv4 and IPv6
::: Preexisting ad list /etc/pihole/adlists.list detected ((exiting setup_blocklists early))
https://raw.githubusercontent.com/StevenBlack/hosts/master/hosts
https://mirror1.malwaredomains.com/files/justdomains
https://s3.amazonaws.com/lists.disconnect.me/simple_tracking.txt
https://s3.amazonaws.com/lists.disconnect.me/simple_ad.txt
::: Testing pihole-FTL DNS: FTL started!
::: Testing lighttpd config: Syntax OK
::: All config checks passed, cleared for startup ...
 ::: Docker start setup complete
  [i] Neutrino emissions detected...
  [✓] Pulling blocklist source list into range

  [✓] Preparing new gravity database
  [i] Target: https://raw.githubusercontent.com/StevenBlack/hosts/master/hosts
  [✓] Status: Retrieval successful
  [i] Received 57380 domains

  [i] Target: https://mirror1.malwaredomains.com/files/justdomains
  [✓] Status: No changes detected
  [i] Received 26854 domains

  [i] Target: http://sysctl.org/cameleon/hosts
  [✓] Status: No changes detected
  [i] Received 20567 domains

  [i] Target: https://s3.amazonaws.com/lists.disconnect.me/simple_tracking.txt
  [✓] Status: No changes detected
  [i] Received 38 domains, 3 domains invalid!
      Sample of invalid domains:
      - # Basic tracking list by Disconnect
      - # License: GPLv3
      - # Contact: support [at] disconnect.me

  [i] Target: https://s3.amazonaws.com/lists.disconnect.me/simple_ad.txt
  [✓] Status: No changes detected
  [i] Received 2701 domains

  [i] Target: https://hosts-file.net/ad_servers.txt
  [✗] Status: Not found
  [✗] List download failed: no cached list available

  [i] Target: https://raw.githubusercontent.com/PolishFiltersTeam/KADhosts/master/KADhosts_without_controversies.txt
  [✓] Status: Retrieval successful
  [i] Received 10829 domains, 2 domains invalid!
      Sample of invalid domains:
      - getin-secure-bank.xyz‎
      - www.getin-secure-bank.xyz‎

  [i] Target: https://raw.githubusercontent.com/FadeMind/hosts.extras/master/add.Spam/hosts
  [✓] Status: Retrieval successful
  [i] Received 73 domains

  [i] Target: https://v.firebog.net/hosts/static/w3kbl.txt
  [✓] Status: No changes detected
  [i] Received 776 domains

  [i] Target: https://v.firebog.net/hosts/BillStearns.txt
  [✓] Status: No changes detected
  [i] Received 8778 domains

  [i] Target: https://www.dshield.org/feeds/suspiciousdomains_Low.txt
  [✓] Status: No changes detected
  [i] Received 0 domains

  [i] Target: https://www.dshield.org/feeds/suspiciousdomains_Medium.txt
  [✓] Status: No changes detected
  [i] Received 0 domains

  [i] Target: https://www.dshield.org/feeds/suspiciousdomains_High.txt
  [✓] Status: No changes detected
  [i] Received 0 domains

  [i] Target: https://raw.githubusercontent.com/matomo-org/referrer-spam-blacklist/master/spammers.txt
  [✓] Status: Retrieval successful
  [i] Received 1911 domains

  [i] Target: https://someonewhocares.org/hosts/zero/hosts
  [✓] Status: No changes detected
  [i] Received 14448 domains, 1 domains invalid!
      Sample of invalid domains:
      - secret.ɢoogle.com

  [i] Target: https://raw.githubusercontent.com/vokins/yhosts/master/hosts
  [✓] Status: Retrieval successful
  [i] Received 8929 domains

  [i] Target: https://winhelp2002.mvps.org/hosts.txt
  [✓] Status: No changes detected
  [i] Received 9953 domains

  [i] Target: https://hosts.nfz.moe/basic/hosts
  [✓] Status: Retrieval successful
  [i] Received 4823 domains

  [i] Target: https://raw.githubusercontent.com/RooneyMcNibNug/pihole-stuff/master/SNAFU.txt
  [✓] Status: Retrieval successful
  [i] Received 37357 domains

  [i] Target: https://ssl.bblck.me/blacklists/hosts-file.txt
  [✓] Status: No changes detected
  [i] Received 550 domains

  [i] Target: https://hostsfile.mine.nu/hosts0.txt
  [✓] Status: No changes detected
  [i] Received 105863 domains, 5 domains invalid!
      Sample of invalid domains:
      - hashbag.cc:8688
      - my?therw?llet.com
      - m?eth?rwall?t.com
      - server.com:1234
      - domain=myway.com

  [i] Target: https://www.joewein.net/dl/bl/dom-bl-base.txt
  [✓] Status: No changes detected
  [i] Received 65493 domains, 1 domains invalid!
      Sample of invalid domains:
      - bzgh.jmeu.cc:9999

  [i] Target: https://v.firebog.net/hosts/Kowabit.txt
  [✓] Status: No changes detected
  [i] Received 7645 domains

  [i] Target: https://adblock.mahakala.is
  [✓] Status: No changes detected
  [i] Received 71194 domains

  [i] Target: https://adaway.org/hosts.txt
  [✓] Status: No changes detected
  [i] Received 12083 domains

  [i] Target: https://v.firebog.net/hosts/AdguardDNS.txt
  [✓] Status: No changes detected
  [i] Received 35851 domains

  [i] Target: https://raw.githubusercontent.com/anudeepND/blacklist/master/adservers.txt
  [✓] Status: Retrieval successful
  [i] Received 42594 domains

  [i] Target: https://v.firebog.net/hosts/Easylist.txt
  [✓] Status: No changes detected
  [i] Received 2834 domains

  [i] Target: https://pgl.yoyo.org/adservers/serverlist.php?hostformat=hosts&showintro=0&mimetype=plaintext
  [✓] Status: No changes detected
  [i] Received 3459 domains

  [i] Target: https://raw.githubusercontent.com/FadeMind/hosts.extras/master/UncheckyAds/hosts
  [✓] Status: Retrieval successful
  [i] Received 10 domains

  [i] Target: https://raw.githubusercontent.com/bigdargon/hostsVN/master/hosts
  [✓] Status: Retrieval successful
  [i] Received 18780 domains

  [i] Target: https://raw.githubusercontent.com/jdlingyu/ad-wars/master/hosts
  [✓] Status: Retrieval successful
  [i] Received 1708 domains

  [i] Target: https://v.firebog.net/hosts/Easyprivacy.txt
  [✓] Status: No changes detected
  [i] Received 2675 domains

  [i] Target: https://v.firebog.net/hosts/Prigent-Ads.txt
  [✓] Status: No changes detected
  [i] Received 3670 domains

  [i] Target: https://gitlab.com/quidsup/notrack-blocklists/raw/master/notrack-blocklist.txt
  [✓] Status: Retrieval successful
  [i] Received 13354 domains

  [i] Target: https://raw.githubusercontent.com/FadeMind/hosts.extras/master/add.2o7Net/hosts
  [✓] Status: Retrieval successful
  [i] Received 1286 domains

  [i] Target: https://raw.githubusercontent.com/crazy-max/WindowsSpyBlocker/master/data/hosts/spy.txt
  [✓] Status: Retrieval successful
  [i] Received 364 domains

  [i] Target: https://www.github.developerdan.com/hosts/lists/ads-and-tracking-extended.txt
  [✓] Status: No changes detected
  [i] Received 166132 domains

  [i] Target: https://hostfiles.frogeye.fr/firstparty-trackers-hosts.txt
  [✓] Status: No changes detected
  [i] Received 36900 domains

  [i] Target: https://hostfiles.frogeye.fr/multiparty-trackers-hosts.txt
  [✓] Status: No changes detected
  [i] Received 47682 domains

  [i] Target: https://raw.githubusercontent.com/Perflyst/PiHoleBlocklist/master/android-tracking.txt
  [✓] Status: Retrieval successful
  [i] Received 80 domains

  [i] Target: https://raw.githubusercontent.com/Perflyst/PiHoleBlocklist/master/SmartTV.txt
  [✓] Status: Retrieval successful
  [i] Received 202 domains

  [i] Target: https://raw.githubusercontent.com/Perflyst/PiHoleBlocklist/master/AmazonFireTV.txt
  [✓] Status: Retrieval successful
  [i] Received 17 domains

  [i] Target: https://v.firebog.net/hosts/Airelle-trc.txt
  [✓] Status: No changes detected
  [i] Received 50352 domains

  [i] Target: https://raw.githubusercontent.com/DandelionSprout/adfilt/master/Alternate%20versions%20Anti-Malware%20List/AntiMalwareHosts.txt
  [✓] Status: Retrieval successful
  [i] Received 130 domains

  [i] Target: https://osint.digitalside.it/Threat-Intel/lists/latestdomains.txt
  [✓] Status: No changes detected
  [i] Received 2093 domains

  [i] Target: https://s3.amazonaws.com/lists.disconnect.me/simple_malvertising.txt
  [✓] Status: No changes detected
  [i] Received 2735 domains

  [i] Target: https://v.firebog.net/hosts/Prigent-Crypto.txt
  [✓] Status: No changes detected
  [i] Received 8624 domains

  [i] Target: https://v.firebog.net/hosts/Prigent-Malware.txt
  [✓] Status: No changes detected
  [i] Received 58044 domains

  [i] Target: https://mirror.cedia.org.ec/malwaredomains/immortal_domains.txt
  [✓] Status: No changes detected
  [i] Received 3196 domains

  [i] Target: https://www.malwaredomainlist.com/hostslist/hosts.txt
  [✓] Status: No changes detected
  [i] Received 1104 domains

  [i] Target: https://bitbucket.org/ethanr/dns-blacklists/raw/8575c9f96e5b4a1308f2f12394abd86d0927a4a0/bad_lists/Mandiant_APT1_Report_Appendix_D.txt
  [✓] Status: No changes detected
  [i] Received 2046 domains

  [i] Target: https://phishing.army/download/phishing_army_blocklist_extended.txt
  [✓] Status: No changes detected
  [i] Received 13883 domains

  [i] Target: https://gitlab.com/quidsup/notrack-blocklists/raw/master/notrack-malware.txt
  [✓] Status: Retrieval successful
  [i] Received 367 domains

  [i] Target: https://v.firebog.net/hosts/Shalla-mal.txt
  [✓] Status: No changes detected
  [i] Received 19593 domains

  [i] Target: https://raw.githubusercontent.com/Spam404/lists/master/main-blacklist.txt
  [✓] Status: Retrieval successful
  [i] Received 8184 domains

  [i] Target: https://raw.githubusercontent.com/FadeMind/hosts.extras/master/add.Risk/hosts
  [✓] Status: Retrieval successful
  [i] Received 2568 domains

  [i] Target: https://urlhaus.abuse.ch/downloads/hostfile/
  [✓] Status: Retrieval successful
  [i] Received 974 domains

  [i] Target: https://raw.githubusercontent.com/HorusTeknoloji/TR-PhishingList/master/url-lists.txt
  [✓] Status: Retrieval successful
  [i] Received 278817 domains

  [i] Target: https://v.firebog.net/hosts/Airelle-hrsk.txt
  [✓] Status: No changes detected
  [i] Received 47743 domains

  [i] Target: https://raw.githubusercontent.com/chadmayfield/my-pihole-blocklists/master/lists/pi_blocklist_porn_all.list
  [✓] Status: Retrieval successful
[cont-finish.d] executing container finish scripts...
[cont-finish.d] done.
[s6-finish] waiting for services.
[s6-finish] sending all processes the TERM signal.
[s6-finish] sending all processes the KILL signal and exiting.

**Comment by 11jwolfe2** [comment]
This is what I get when I simply change 5.0 to 4.4 in the pihole.values.yml file and use helm install.


[s6-init] making user provided files available at /var/run/s6/etc...exited 0.
[s6-init] ensuring user provided files have correct perms...exited 0.
[fix-attrs.d] applying ownership & permissions fixes...
[fix-attrs.d] 01-resolver-resolv: applying... 
[fix-attrs.d] 01-resolver-resolv: exited 0.
[fix-attrs.d] done.
[cont-init.d] executing container initialization scripts...
[cont-init.d] 20-start.sh: executing... 
 ::: Starting docker specific checks & setup for docker pihole/pihole
OK: Checks passed for /etc/resolv.conf DNS servers

nameserver 127.0.0.1
nameserver 8.8.8.8
  [i] Existing PHP installation detected : PHP version 7.0.33-0+deb9u7

  [i] Installing configs from /etc/.pihole...
  [i] Existing dnsmasq.conf found... it is not a Pi-hole file, leaving alone!
  [✓] Copying 01-pihole.conf to /etc/dnsmasq.d/01-pihole.conf
chown: changing ownership of '/etc/pihole/pihole-FTL.conf': Operation not permitted
chown: changing ownership of '/etc/pihole/regex.list': Operation not permitted
chown: changing ownership of '/etc/pihole': Operation not permitted
chown: cannot access '/etc/pihole/dhcp.leases': No such file or directory
::: Pre existing WEBPASSWORD found
Using default DNS servers: 8.8.8.8 & 8.8.4.4
DNSMasq binding to default interface: eth0
Added ENV to php:
			"PHP_ERROR_LOG" => "/var/log/lighttpd/error.log",
			"ServerIP" => "0.0.0.0",
			"VIRTUAL_HOST" => "pi.hole",
Using IPv4 and IPv6
::: Preexisting ad list /etc/pihole/adlists.list detected ((exiting setup_blocklists early))
https://raw.githubusercontent.com/StevenBlack/hosts/master/hosts
https://mirror1.malwaredomains.com/files/justdomains
https://s3.amazonaws.com/lists.disconnect.me/simple_tracking.txt
https://s3.amazonaws.com/lists.disconnect.me/simple_ad.txt
::: Testing pihole-FTL DNS: FTL started!
::: Testing lighttpd config: Syntax OK
::: All config checks passed, cleared for startup ...
 ::: Docker start setup complete
  [i] Pi-hole blocking is enabled
  [i] Neutrino emissions detected...
  [✓] Pulling blocklist source list into range

  [i] Target: raw.githubusercontent.com (hosts)
  [✓] Status: Retrieval successful

  [i] Target: mirror1.malwaredomains.com (justdomains)
  [✓] Status: No changes detected

  [i] Target: s3.amazonaws.com (simple_tracking.txt)
  [✓] Status: No changes detected

  [i] Target: s3.amazonaws.com (simple_ad.txt)
  [✓] Status: No changes detected

  [✓] Consolidating blocklists
  [✓] Extracting domains from blocklists
  [i] Number of domains being pulled in by gravity: 84217
  [✓] Removing duplicate domains
  [i] Number of unique domains trapped in the Event Horizon: 84115
  [i] Nothing to whitelist!
  [i] Number of regex filters: 0
  [✓] Parsing domains into hosts format
  [✓] Cleaning up stray matter

  [✓] DNS service is running
  [✓] Pi-hole blocking is Enabled
[cont-init.d] 20-start.sh: exited 0.
[cont-init.d] done.
[services.d] starting services
Starting pihole-FTL (no-daemon) as root
Starting lighttpd
[services.d] done.
Starting crond

**Comment by 11jwolfe2** [comment]
you can close this issue, I found that is you add to many lists it breaks my set up, limiting them made it install properly I am also having the issue shown in issue #39 though.

**Comment by MoJo2600** [comment]
Good to know
