### ISSUE TITLE
Local DNS Records aren't reachable 

### ISSUE THREAD

**Issue by Henrik-Wo** [MoJo2600/pihole-kubernetes#61]
As soon as I create a local DNS entry, the page/server is no longer accessible locally. When I install pi-hole on a single RPI, local entries work fine.

**Comment by MoJo2600** [comment]
Can you post your configuration please?

**Comment by Henrik-Wo** [comment]
I was able to partially solve the problem. Now use a defined 'loadBalancerIP`. However, the problem still exists when I connect to my LAN via VPN. The AddBlocker still works, but the local DNS entries are not accessible...

I attached my 'values.yml'.

[pihole.values.yml.txt](https://github.com/MoJo2600/pihole-kubernetes/files/5006593/pihole.values.yml.txt)

**Comment by MoJo2600** [comment]
Hm... i'm not sure I can help with this. This might be more of an pihole issue or and VPN configuration issue than an pihole on kubernetes issue?

**Comment by MoJo2600** [comment]
I will close this issue due to inactivity. If you have further questions, please feel free to open it again.
