### ISSUE TITLE
Restart fails for pihole

### ISSUE THREAD

**Issue by 11jwolfe2** [MoJo2600/pihole-kubernetes#76]
So this is an issue I have been having since first using this container. Whenever my container bricks and is restarted it continues to restart because it fails when loading my adlists. When using the `kubectl logs (podName) -f` I can see the container going out and loading in the blocklists and after adding a few it fails and reboots, not always at the same list. Sometimes it loads them all then the container reboots. If I delete my persistent volume it will start up just fine. I then change the folder permissions (this is the www-data #39 ) user issue we've discussed here a lot. Then add the lists manual through the web interface and everything is fine until it restarts. Once it restarts it fails until I repeat this process.

**Comment by brnl** [comment]
How long does it take to start? Maybe you should increase the probes.readiness.initialDelaySeconds to something higher than 60.

**Comment by MoJo2600** [comment]
Yes, this is a issue that i face as well. I have to test the `initialDelaySeconds` as well.

**Comment by 11jwolfe2** [comment]
Updated both p`robes.liveness.initialDelaySecond` and `probes.readiness.initialDelaySecond` to 480 and it started properly after helm upgrade.
