### ISSUE TITLE
Rework services

### ISSUE THREAD

**Issue by dza89** [MoJo2600/pihole-kubernetes#90]
Right now there is a tcp and a udp service.

I think it makes more sense to have three services:

1. webservice
2. dhcp service
3. dns service

I will make the MR if you agree, but i don't really know the background behind the separation in tcp and udp, so I thought I would ask first.

**Comment by dza89** [comment]
Or just one service with three blocks in it and then if .value.webservice enabled etc.

**Comment by MoJo2600** [comment]
The reason behind the separation is, that the Loadbalancers are bound to one protocol. You can either have a TCP or an UDP Loadbalancer. As long as we can not have mixed protocol load balancers, we have to keep them separated.

There is already another PR to separate the loadbalancers to make them more compatible to traefik [81](https://github.com/MoJo2600/pihole-kubernetes/pull/81) - but I'm waiting for an answer of the contributor to integrate my changes.
