### ISSUE TITLE
doh enabled pods do not stay ready

### ISSUE THREAD

**Issue by vavallee** [MoJo2600/pihole-kubernetes#98]
Hiya!
Chart works great with pihole, however if I set doh to enabled (leaving the rest of the config as-is), the container does not become ready, and DNS resolution does not work in pihole.
If I describe the container I get:

`Container cloudflared failed liveness probe, will be restarted`

All there is in the container log for cloudflared is:

```
[36mINFO^[0m[2020-12-22T17:45:09Z] Adding DNS upstream - url: https://1.1.1.1/dns-query

[36mINFO^[0m[2020-12-22T17:45:09Z] Adding DNS upstream - url: https://1.0.0.1/dns-query

[36mINFO^[0m[2020-12-22T17:45:09Z] Starting DNS over HTTPS proxy server on: dns://0.0.0.0:5053

[36mINFO^[0m[2020-12-22T17:45:09Z] Starting metrics server on [::]:49312/metrics
```

**Comment by vavallee** [comment]
What's more weird, is in the describe, 1 success and many failures in the liveness
`
 Liveness:     exec [/usr/bin/nc -uzvw3 localhost 5053] delay=0s timeout=1s period=10s #success=1 #failure=3`

**Comment by MoJo2600** [comment]
I'm sorry, but I can't help you with this. I did not test this setup. I hope one of the other users who have doh enabled can help?

**Comment by i5Js** [comment]
I have the same problem, my pods works fine, but the syslog is full of those lines and stuck my node.

**Comment by sam-kleiner** [comment]
I have doh enabled and it is working without issue. I redeployed my setup last night from a very old version of this chart.

My logs look *almost* identical to @vavallee, but the last two lines are flipped. Possible the image changed recently. Might help to set `doh.pullPolicy = true` and redeploy to force the update. 

```
INFO[2021-01-02T04:58:56Z] Adding DNS upstream - url: https://1.1.1.1/dns-query
INFO[2021-01-02T04:58:56Z] Adding DNS upstream - url: https://1.0.0.1/dns-query
INFO[2021-01-02T04:58:56Z] Starting metrics server on [::]:49312/metrics
INFO[2021-01-02T04:58:56Z] Starting DNS over HTTPS proxy server on: dns://0.0.0.0:5053
```

**Comment by vavallee** [comment]
I do suspect the issue is because of a new image for the cloudfared image.
I have manually disabled the liveness prove for that container, and it seems to run perfectly. I am not sure what's up with that probe. Maybe it's starting too quickly for my cluster?

`/ $ /usr/bin/nc -uzvw3 localhost 5053
localhost ([::1]:5053) open
/ $ /usr/bin/nc -uzvw3 localhost 5053
localhost ([::1]:5053) open
/ $ dig @127.0.0.1 -p 5053 google.com

; <<>> DiG 9.16.6 <<>> @127.0.0.1 -p 5053 google.com
; (1 server found)
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 32996
;; flags: qr rd ra; QUERY: 1, ANSWER: 1, AUTHORITY: 0, ADDITIONAL: 1

;; OPT PSEUDOSECTION:
; EDNS: version: 0, flags:; udp: 4096
;; QUESTION SECTION:
;google.com.                    IN      A

;; ANSWER SECTION:
google.com.             251     IN      A       172.217.9.238

;; Query time: 31 msec
;; SERVER: 127.0.0.1#5053(127.0.0.1)
;; WHEN: Sat Jan 02 20:38:25 UTC 2021
;; MSG SIZE  rcvd: 65
`

**Comment by i5Js** [comment]
I've uninstalled, because my node is completely stuck. 

@vavallee where can I disable the liveness? probes section in values template?

Thanks

**Comment by vavallee** [comment]
I did it by editing the deploy manually.
`kubectl edit deploy pi-pihole` 
and setting
`initialDelaySeconds: 120` 
to see if the liveness is starting too fast

**Comment by i5Js** [comment]
I've disabled it editing the deploy. Now the node is alive and no errors.

**Comment by vavallee** [comment]
Agreed. It doesn't restart at all if the probe is disabled. But Even setting the `initialDelaySeconds` and `periodSeconds` to higher numbers didn't seem to stop the probe from failing, I think I'll need to play with the numbers. Very strange.

**Comment by i5Js** [comment]
Awesome, all my problems in my k3s cluster was because of this, now, everything is working flawless. Fingers cross!

**Comment by MoJo2600** [comment]
Does it work now? If so, we could close this issue.

**Comment by i5Js** [comment]
I don't think so. I have always to modify the deployment en remove the liveness in the DOH container.

**Comment by i5Js** [comment]
Hello @MoJo2600 I've already tested the last chart. It work flawless at least in my cluster, so I guess this issue could be archived

**Comment by MoJo2600** [comment]
Awesome, if there is anything else, open this issue again please.
